---
Name: spindb-envcheck
---
EnvironmentCheckSuite:
  registered_suites:
    health:
      - spindb
  registered_checks:
    spindb:
      definition: 'LittleGiant\SpinDB\Health\BackupCheck'
      title: 'Is the database backup saving to S3 daily?'
