---
Name: spindb-envcheck
---
SilverStripe\EnvironmentCheck\EnvironmentCheckSuite:
  registered_checks:
    spindb:
      definition: 'LittleGiant\SpinDB\Health\BackupCheck'
      title: 'Is the database backup saving to S3 daily?'
  registered_suites:
    check:
    - spindb
